version: '3'
services: 
  lwpd1:
    image:  wordpress
    container_name: lwpd1
    environment: 
      WORDPRESS_DB_HOST: ldbd1:3306
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME:  ${DB_DATABASE}      
      WORDPRESS_DB_PASSWPORD: password
    ports:
      - 80:80
    depends_on: 
      - ldbd1
    networks:
      - netd1
  ldbd1:
    image: mysql:5.7
    container_name: ldbd1
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - 3306:3006
    networks:
      - netd1      
networks:
  netd1:
    driver: bridge
